name: PotionFood
version: '1.5'
main: me.mvk.potionFood.PotionFoodPlugin
api-version: '1.21'
commands:
  potionfood:
    usage: /potionfood reload
    description: Reload PotionFood config
    permission: potionfood.reload

permissions:
  potionfood.reload:
    default: op